version: '3.9'
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: cdndb
      POSTGRES_USER: cdndbuser
      POSTGRES_PASSWORD: cdndbpassword
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "cdndb", "-U", "cdndbuser"]
      interval: 10s
      start_period: 30s
  cdn:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "8887:8887"
    depends_on:
      - postgres
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    depends_on:
      - cdn
volumes:
  data: